CREATE TABLE USERS (
    ID INT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    AGE INT
)

CREATE TABLE PRODUCTS (
    ID INT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(200),
    PRICE REAL,
)

CREATE TABLE REQUESTS (
    ID INT PRIMARY KEY,
    DESCRIPTION VARCHAR(250),
    QUANTITY INT NOT NULL,
    PRODUCT_ID INT
    USER_ID INT,

    FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(ID)
)
